# Generated by Django 5.2.4 on 2025-07-10 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_prompt', models.TextField()),
                ('base_html_code', models.TextField()),
                ('content_data', models.JSONField(default=dict)),
                ('final_html_code', models.TextField(blank=True, null=True)),
                ('name', models.CharField(default='Novo Site', max_length=255)),
                ('published_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
