# Generated by Django 5.2.4 on 2025-07-18 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_siteproject_options_alter_siteproject_name_and_more'),
        ('solar', '0020_alter_projeto_cliente_alter_projeto_descricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteproject',
            name='original_prompt',
        ),
        migrations.AddField(
            model_name='siteproject',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_projects', to='solar.cliente'),
        ),
        migrations.AlterField(
            model_name='siteproject',
            name='name',
            field=models.CharField(default='Novo Site', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteproject',
            name='published_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
