# Generated by Django 5.2.4 on 2025-07-21 11:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_siteproject_original_prompt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteproject',
            old_name='cliente',
            new_name='cliente_associado',
        ),
        migrations.AddField(
            model_name='siteproject',
            name='original_prompt',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteproject',
            name='published_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='siteproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaya_site_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
