# Generated by Django 5.2.2 on 2025-06-12 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item do Pedido', 'verbose_name_plural': 'Itens do Pedido'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AddField(
            model_name='item',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Unitário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='stripe_product_id',
            field=models.CharField(default=0.0, max_length=255, verbose_name='ID Produto Stripe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Subtotal do Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='email_cliente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email do Cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('processando', 'Processando'), ('enviado', 'Enviado'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], default='pendente', max_length=20, verbose_name='Status do Pedido'),
        ),
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='produtos.pedido', verbose_name='Pedido Relacionado'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado Em'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='stripe_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='ID da Sessão Stripe'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
