# Generated by Django 5.2.2 on 2025-06-13 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_remove_carouselimage_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['name'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AddField(
            model_name='produto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado Em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU (Código do Produto)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (URL Amigável)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Estoque'),
        ),
        migrations.AddField(
            model_name='produto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Categoria (URL-friendly)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='images',
            field=models.JSONField(blank=True, null=True, verbose_name='URLs das Imagens (JSON)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
    ]
