# Generated by Django 5.2.2 on 2025-06-13 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produto_options_produto_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='images',
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='image',
            field=models.ImageField(upload_to='carousel/'),
        ),
        migrations.CreateModel(
            name='ProdutoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produtos/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto Alternativo')),
                ('is_main', models.BooleanField(default=False, verbose_name='Imagem Principal')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Imagem do Produto',
                'verbose_name_plural': 'Imagens do Produto',
                'ordering': ['-is_main', 'id'],
            },
        ),
    ]
