# Generated by Django 5.2.2 on 2025-06-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_remove_produto_images_carouselimage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='produto_id_original',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID do Produto Original (Django)'),
        ),
        migrations.DeleteModel(
            name='ArquivoImpressao',
        ),
    ]
