"""
Django settings for energia_solar project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import smtplib
# Linha original que causava o erro: from decouple import config
# Corrija para importar Config e RepositoryEnv
# from decouple import Config, RepositoryEnv
from pathlib import Path
# import dj_database_url 
BASE_DIR = Path(__file__).resolve().parent.parent

STRIPE_SECRET_KEY = 'sk_test_51PnlTd07MXniEPOQGMO7NYQGJbZKmfEFFljlCH4PS8RDyYKKka91CH3obqsM1gBZXydb6vbWl1fHHpsI3J7Ijue500IwRgQ9i9'
# Build paths inside the project like this: BASE_DIR / 'subdir'.
# config = Config(RepositoryEnv(str(BASE_DIR / '.env')))
# config = Config(RepositoryEnv(str(BASE_DIR / '.env')))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = 'django-insecure-k^#8#26p1!^!_tk+f!gcxezrnri2e#m)9+o@=#&0iu^%8848au'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
# DEBUG = config('DEBUG', default=False, cast=bool)
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'solar',
    'widget_tweaks',
    'produtos',
    'django_admin_logs',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.sites.middleware.CurrentSiteMiddleware',

]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)
# energia_solar/settings.py

# ...
LOGIN_URL = 'account_login' # <--- CORRIGIR AQUI!
LOGIN_REDIRECT_URL = 'produtos:home' # Exemplo: Redirecionar para a home da loja
LOGOUT_REDIRECT_URL = 'account_login' # <--- CORRIGIR AQUI!
ACCOUNT_LOGOUT_REDIRECT_URL = 'account_login' # Esta já estava correta para Allauth

# ...

# Configurações adicionais
ACCOUNT_AUTHENTICATION_METHOD = 'username'
ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_USERNAME_REQUIRED = True


SITE_ID = 1

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # ou outra backend de sessão
SESSION_COOKIE_SECURE = False  # Apenas True em produção
SESSION_COOKIE_HTTPONLY = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

ROOT_URLCONF = 'energia_solar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'energia_solar.wsgi.application'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-mail.outlook.com'  # Servidor SMTP do Hotmail
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'mauriciodiassilva@hotmail.com'  # Seu e-mail do Hotmail
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_HOST_PASSWORD = 'EuSouoEuSou01@'  # Sua senha do Hotmail
# Opcional, para definir um remetente padrão
DEFAULT_FROM_EMAIL = 'mauriciodiassilva@hotmail.com'



# sender = "mauriciodiassilva@hotmail.com"
# password = "EuSouoEuSou01@"  # Replace with your app password

# try:
#     server = smtplib.SMTP("smtp-mail.outlook.com", 587)  # Or 465 if using SSL
#     server.starttls()  # Or server = smtplib.SMTP_SSL("smtp-mail.outlook.com", 465) if using SSL
#     server.login(sender, password)
#     print("Successfully connected to SMTP server.")
# except Exception as e:
#     print(f"Error connecting to SMTP server: {e}")
# finally:
#     server.quit() if server else None



# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

####### INÍCIO DAS CONFIGURAÇÕES DO DB SQLITE #############
DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.sqlite3',
       'NAME': BASE_DIR / 'db.sqlite3',
   }
}
############ FIM DAS CONFIGURAÇÕES DB SQLITE ##############

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'mydb',
#         'USER': 'user',
#         'PASSWORD': 'password',
#         'HOST': 'db',  # mesmo nome do serviço no docker-compose
#         'PORT': '3306',
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True


# Configurações de mídia
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configurações de arquivos estáticos
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'staticfiles')]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


