"""
Django settings for energia_solar project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

# --- INÍCIO DA CONFIGURAÇÃO COM DJANGO-ENVIRON ---
import environ # <--- Importe environ
# Initialise environment variables

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

env = environ.Env() # <--- Crie uma instância de Env

# Read .env file from the project root (where manage.py is)
# BASE_DIR é 'C:/Users/Mauricio/Desktop/crmsolar'
env.read_env(os.path.join(BASE_DIR, '.env')) # <--- Lê o arquivo .env
# --- FIM DA CONFIGURAÇÃO COM DJANGO-ENVIRON --

STRIPE_SECRET_KEY = env('SECRET_KEY_STRIPE')

SECRET_KEY = env('SECRET_KEY', default='sua-chave-secreta-padrao-para-desenvolvimento-aqui') # <--- Use env()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=False, cast=bool) # <--- Use env()
DEBUG='True'

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[]) # <--- Exemplo para ALLOWED_HOSTS
# ALLOWED_HOSTS=()
# ... (o restante do seu settings.py) ...

SITE_ID = 1
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'solar',
    'widget_tweaks',
    'produtos',
    'pagamento',
    'django_admin_logs',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.sites.middleware.CurrentSiteMiddleware',

]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)
# energia_solar/settings.py

# ...
LOGIN_URL = 'account_login' # <--- CORRIGIR AQUI!
LOGIN_REDIRECT_URL = 'produtos:home' # Exemplo: Redirecionar para a home da loja
LOGOUT_REDIRECT_URL = 'account_login' # <--- CORRIGIR AQUI!
ACCOUNT_LOGOUT_REDIRECT_URL = 'account_login' # Esta já estava correta para Allauth

# ...

# Configurações adicionais
ACCOUNT_AUTHENTICATION_METHOD = 'username'
ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_USERNAME_REQUIRED = True


SITE_ID = 1

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # ou outra backend de sessão
SESSION_COOKIE_SECURE = False  # Apenas True em produção
SESSION_COOKIE_HTTPONLY = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

ROOT_URLCONF = 'energia_solar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR , 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'energia_solar.wsgi.application'



# Configuração de E-mail com django-environ
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='smtp-mail.outlook.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587) # env.int() para converter para inteiro
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True) # env.bool() para booleanos
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=False)
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD') # Aqui virá a senha de aplicativo
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')



# sender = "mauriciodiassilva@hotmail.com"
# password = "EuSouoEuSou01@"  # Replace with your app password

# try:
#     server = smtplib.SMTP("smtp-mail.outlook.com", 587)  # Or 465 if using SSL
#     server.starttls()  # Or server = smtplib.SMTP_SSL("smtp-mail.outlook.com", 465) if using SSL
#     server.login(sender, password)
#     print("Successfully connected to SMTP server.")
# except Exception as e:
#     print(f"Error connecting to SMTP server: {e}")
# finally:
#     server.quit() if server else None



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # Mude esta linha:
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'), # <-- CORRIGIDO AQUI
    }
}



# Configuração do Banco de Dados com django-environ (Muito comum e recomendado)
# Isso permite que você coloque a string completa do banco de dados no .env
# DATABASES = {
#     'default': env.db_url(
#         'DATABASE_URL',
#         default='sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3') # Default para SQLite em dev
#     )
# }
# NO SEU ARQUIVO .env, você teria algo como:
# DATABASE_URL=mysql://user:password@db:3306/mydb
# Ou, para PostgreSQL: DATABASE_URL=postgres://user:password@host:port/dbname
########### FIM DAS CONFIGURAÇÕES DB SQLITE ##############

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'mydb',
#         'USER': 'user',
#         'PASSWORD': 'password',
#         'HOST': 'db',  # mesmo nome do serviço no docker-compose
#         'PORT': '3306',
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True


# Configurações de mídia
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configurações de arquivos estáticos
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


