# Generated by Django 5.2 on 2025-04-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0002_projeto_data_fim_alter_projeto_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
