# Generated by Django 5.2 on 2025-04-19 06:40

import solar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0003_cliente_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[solar.models.validar_cnpj]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=20, validators=[solar.models.validar_telefone]),
        ),
    ]
