# Generated by Django 5.2 on 2025-04-22 21:55

import solar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0004_alter_cliente_cnpj_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[solar.models.validar_cnpj]),
        ),
    ]
