# Generated by Django 5.2.1 on 2025-05-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0009_etapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('unidade_medida', models.CharField(choices=[('un', 'Unidade'), ('m', 'Metro'), ('kg', 'Quilo'), ('l', 'Litro')], max_length=20)),
                ('quantidade_estoque', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
