# Generated by Django 5.2.1 on 2025-05-29 07:54

import solar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0010_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18, validators=[solar.models.validar_cnpj])),
                ('telefone', models.CharField(max_length=20, validators=[solar.models.validar_telefone])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.TextField(blank=True)),
            ],
        ),
    ]
