# Generated by Django 5.2.1 on 2025-05-29 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0011_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recebimento', 'Recebimento'), ('pagamento', 'Pagamento')], max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], max_length=20)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='solar.projeto')),
            ],
        ),
    ]
