# Generated by Django 5.2.1 on 2025-05-29 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0012_lancamentofinanceiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_acesso', models.CharField(max_length=20, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acesso', to='solar.cliente')),
            ],
        ),
    ]
