# Generated by Django 5.2.1 on 2025-05-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0014_cliente_id_acesso_cliente_senha_acesso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='descricao',
        ),
        migrations.AddField(
            model_name='material',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='data_entrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='material',
            name='garantia_ate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='preco_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='preco_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='fabricante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantidade_estoque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='unidade_medida',
            field=models.CharField(max_length=20),
        ),
    ]
