# Generated by Django 5.2.1 on 2025-05-30 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0015_remove_material_descricao_material_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='endereco_instalacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solar.fornecedor'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='inversor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo do Inversor'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='potencia_kwp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Potência (kWp)'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='quantidade_modulos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de Módulos'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Total (R$)'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluído', 'Concluído'), ('Aguardando aprovação', 'Aguardando aprovação'), ('Cancelado', 'Cancelado')], max_length=50),
        ),
    ]
