# Generated by Django 5.2.1 on 2025-05-30 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0016_projeto_endereco_instalacao_projeto_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Documento')),
                ('arquivo', models.FileField(upload_to='projetos/%Y/%m/%d/', verbose_name='Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('visivel_cliente', models.BooleanField(default=False, verbose_name='Visível para o cliente?')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='solar.projeto')),
            ],
        ),
    ]
