# Generated by Django 5.2.4 on 2025-07-06 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0019_remove_cliente_endereco_cliente_cep_cliente_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solar.cliente'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
